Update .drone.yml

diff --git a/.drone.yml b/.drone.yml
--- a/.drone.yml
+++ b/.drone.yml
@@ -72,7 +72,7 @@ steps:
         tar -czf "/$${LOKI_DIR}/loki-docker-driver-$${VERSION}.tar.gz" \
             -C "$${TEMP_DIR}" rootfs config.json
       else
-        echo "[!] Loki Logging Driver ID not found." | tee -a "$${TG_TEMPLATE}"
+        echo "[!] Loki Logging Driver ID not found." | tee -a "$${TG_TEMPLATE}" && exit 1
       fi
     - echo "[done] - $${DRONE_STEP_NAME}" | tee -a "$${TG_TEMPLATE}"
   depends_on:
@@ -102,7 +102,7 @@ steps:
     ARCH: x86_64
     RELEASE: 1.1.1
     OUTPUT_TYPE: rpm
-    INPUT_TYPE: dirz
+    INPUT_TYPE: dir
     LICENSE: GNU GPL
     LOG: error
   volumes:
@@ -130,7 +130,7 @@ steps:
         --log "$${LOG}" \
         --description "Средство для автоматизированного обновления Docker-контейнеров 🤓" \
         --url "https://dev.gnivc.ru/gnivc/nerd/" \
-        -C "$${SRC_DIR}" . 2>&1 | tee -a "$${TG_TEMPLATE}" || exit 1
+        -C "$${SRC_DIR}" . 2>&1 | tee -a "$${TG_TEMPLATE}" && exit 1
   - echo "$${PACKAGE_PATH}" > "$${PKG_PATH}"
   - echo "[done] - $${DRONE_STEP_NAME}" | tee -a "$${TG_TEMPLATE}"
   depends_on:
