Update .drone.yml

diff --git a/.drone.yml b/.drone.yml
--- a/.drone.yml
+++ b/.drone.yml
@@ -133,7 +133,8 @@ steps:
         -C "$${SRC_DIR}" . | grep -E "fatal|error")
   - | 
     if [ -n "$${ERROR}" ]; then \
-      echo "$${ERROR}" | tee -a "$${TG_TEMPLATE}" && exit 1
+      echo "$${ERROR}" \
+      echo "$${ERROR}" | tee -a "$${TG_TEMPLATE}" && exit 1 \
     fi
   #- [ -n echo "$${ERROR}" | grep -E "fatal|error") ] && { echo "$${ERROR}" | tee -a "$${TG_TEMPLATE}"}
   - echo "$${PACKAGE_PATH}" > "$${PKG_PATH}"
